services:
  nuxt-dashboard:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: nuxt-shadcn-dashboard

    restart: unless-stopped

    ports:
      - "3000:3000"
      
    env_file:
      - .env

    environment:
      NODE_ENV: production
      NITRO_HOST: 0.0.0.0
      NITRO_PORT: 3000